# Generated by Django 5.1.7 on 2025-03-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [('can_inactivate', 'Can inactivate'), ('can_canceled_sending', 'Can icanceled sending')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
