# Generated by Django 5.1.7 on 2025-03-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_sending_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ['status'], 'permissions': [('can_canceled_sending', ' ')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailingrecipient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действительный'),
        ),
        migrations.AddField(
            model_name='mailingrecipient',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='sending',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действительный'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='date_attempt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status_attempt',
            field=models.CharField(choices=[('successfully', 'Успешно'), ('unsuccessful', 'Неуспешно')], max_length=15, verbose_name='Статус полытки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending', to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='recipient',
            field=models.ManyToManyField(to='mailing.mailingrecipient', verbose_name='Укажите получателей рассылки'),
        ),
    ]
