# Generated by Django 5.1.7 on 2025-04-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_sending_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'ordering': ['email'], 'permissions': [('can_inactivate', 'Может блокировать пользователя'), ('can_canceled_sending', 'Может блокировать рассылку')], 'verbose_name': 'Получатель рассылки', 'verbose_name_plural': 'Получатели рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_inactivate', 'Может блокировать пользователя'), ('can_canceled_sending', 'Может блокировать рассылку')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ['status'], 'permissions': [('can_inactivate', 'Может блокировать пользователя'), ('can_canceled_sending', 'Может блокировать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
