# Generated by Django 5.1.7 on 2025-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailingrecipient_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='start_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала рассылки'),
        ),
    ]
