# Generated by Django 5.1.7 on 2025-04-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_sending_start_sending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='is_active',
        ),
    ]
